# ========================= Bus Inputs ==========================

# ============ Mandatory ================
service: "PayExe_ProRev_Core_Upda_S"
version: "v1.0"

# Pl_ActiveDirectory => ldap group
ldap:
  DEV: "PAYEXE_PROREV_CORE_UPDA_GD"
  QAS: "PAYEXE_PROREV_CORE_UPDA_GQ"
  PRD: "PAYEXE_PROREV_CORE_UPDA_GP"

# workdiroverride
wdo:
  default:
    app:
      additionalInstances: "10"
      "mTLS.useHTTPS": "yes"
      "Onprem.useHTTPS": "no"
      "HTTP Request.timeoutForServer": "17"
      "mTLS.timeoutForClient": "18"
      "Onprem.timeoutForClient": "18"
      "CTRLAUTHAPP.UDP_USE_CCAS400": "S"
      "mTLS.URLSpecifier" : "/v1.0/mtls/s/paymentexecution/procedurereverse/core/update*"
      "Onprem.URLSpecifier" : "/v1.0/onprem/s/paymentexecution/procedurereverse/core/update*"
      UDP_URL_APIREST: "https://localhost:7843/v1.0"
      UDP_OPERACION_GET: "UpdatePaymentExecutionProcedureReverseCore"
    rest:
      additionalInstances: "10"
      "HTTP Input.useHTTPS": "yes"
      "HTTP Input.timeoutForClient": "16"
      "CTRLINICIAL.UDP_USE_CCAS400": "S"
      UDP_OPERACION_GET: "UpdatePaymentExecutionProcedureReverseCore"



