trigger:
  branches:
    include:
      - feature

# Configura el PR trigger: de cualquier rama 'feature/*' hacia 'dev'
# pr:
#   branches:
#     include:
#       - feature/*
#     target: dev
#   paths:
#     include:
#       - /

resources:
  repositories:
  - repository: common_components
    type: git
    name: PER_Fabrica_BANBIF/common_components
    ref: refs/heads/feature # La rama donde están tus plantillas

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Validation
  displayName: 'Validación de Estructura'
  jobs:
  - template: pipelines/pipelines/commons/validation.yml@common_components

- stage: ConfigCheck
  displayName: 'Validación de Configuraciones'
  dependsOn: Validation
  condition: succeeded()
  jobs:
  - template: pipelines/pipelines/commons/valid-cfg-processor.yml@common_components

- stage: GenerationAndPush
  displayName: 'Generación de XML y Actualización del PR'
  dependsOn: ConfigCheck
  condition: succeeded()
  jobs:
  - template: pipelines/pipelines/commons/generate-xml-push.yml@common_components
    parameters:
      source_folder: 'ci'
      generated_xml: '$(Build.SourcesDirectory)/Monitoring.monprofile.xml'
      variable_group_name: 'Monitoring_XML'
