image:
  name: 047824062623.dkr.ecr.us-west-2.amazonaws.com/us-west-2-ecr-prd-baseline-bash:latest
  aws: 
    oidc-role: arn:aws:iam::047824062623:role/us-west-2-iamRole-prd-devops-core

definitions:
  services:
    docker:
      memory: 3072

pipelines:
  branches:
    '{develop,release,main}':
      - step:
          oidc: true
          services:
            - docker
          script:
            - export AWS_ROLE_ARN="arn:aws:iam::${AWS_ACCOUNT_DEVOPS_ID}:role/us-west-2-iamRole-prd-devops-core" && export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token && echo ${BITBUCKET_STEP_OIDC_TOKEN} > $(pwd)/web-identity-token
            - secret=$(aws secretsmanager get-secret-value --region us-west-2 --secret-id us-west-2-secretsmanager-prd-devops-bitbucket-core --query SecretString --output text)
            - git clone https://x-token-auth:$(echo "${secret}" | jq -r .token)@bitbucket.org/$(echo "${secret}" | jq -r .workspace)/devops-script-core.git -b main .scripts
            - cp .scripts/Makefile ./
            - make init