secret-name=arn:aws:secretsmanager:us-west-2:219964297537:secret:mr-sec-secret-dev-integrations-app213-devops-YVoNgf|arn:aws:secretsmanager:us-east-1:219964297537:secret:mr-sec-secret-dev-integrations-app213-devops-YVoNgf
keys=["credencial12","credencial2"]
